/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaDatos.Usuarios_Personal.datosIniciarSesion;
import CapaLogica.Usuarios_Personal.conexionUsuarios;
import CapaPresentacion.PaginaPrincipal.main.Principal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author KENNY
 */
public class Login extends javax.swing.JFrame {

    int xMouse,  yMouse;
    
    
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        centrarPantalla();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        txtNombreEmpresa = new javax.swing.JLabel();
        LoginIcono1 = new javax.swing.JLabel();
        FondoLogin = new javax.swing.JLabel();
        LoginIcono2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cajaUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cajaContrasena = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JPanel();
        txtIniciarSesion = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreEmpresa.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        txtNombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreEmpresa.setText("EMPRESA DE COMIDA");
        backGround.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 290, -1));

        LoginIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/logoCafe.png"))); // NOI18N
        backGround.add(LoginIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 380, 300));

        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/fondoLogin.jpg"))); // NOI18N
        FondoLogin.setPreferredSize(new java.awt.Dimension(400, 16));
        backGround.add(FondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        LoginIcono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/logoLogin2.png"))); // NOI18N
        backGround.add(LoginIcono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 80, 80));

        txtTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("INICIAR SESION");
        backGround.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setText("USUARIO");
        backGround.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));
        backGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 320, 10));

        cajaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        cajaUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        cajaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        cajaUsuario.setText("Ingresar nombre de usuario");
        cajaUsuario.setBorder(null);
        cajaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaUsuarioMousePressed(evt);
            }
        });
        cajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUsuarioActionPerformed(evt);
            }
        });
        backGround.add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 222, 310, 30));

        txtContrasena.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasena.setText("CONTRASEÑA");
        backGround.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));
        backGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 320, 10));

        cajaContrasena.setBackground(new java.awt.Color(255, 255, 255));
        cajaContrasena.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cajaContrasena.setForeground(new java.awt.Color(204, 204, 204));
        cajaContrasena.setText("*********");
        cajaContrasena.setBorder(null);
        cajaContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaContrasenaMousePressed(evt);
            }
        });
        backGround.add(cajaContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 320, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(211, 165, 129));
        btnIniciarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIniciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        txtIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIniciarSesion.setText("INGRESAR");
        txtIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIniciarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnIniciarSesionLayout = new javax.swing.GroupLayout(btnIniciarSesion);
        btnIniciarSesion.setLayout(btnIniciarSesionLayout);
        btnIniciarSesionLayout.setHorizontalGroup(
            btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
        btnIniciarSesionLayout.setVerticalGroup(
            btnIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        backGround.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 240, 40));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        txtExit.setBackground(new java.awt.Color(255, 255, 255));
        txtExit.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 751, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        backGround.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUsuarioActionPerformed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX(); //me da la posicion en el eje X de la ventana
        yMouse = evt.getY();//me da la posicion en el eje Y de la ventana
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();//esto captura en todo momento donde se encuentra la ventana
         int y = evt.getYOnScreen();
        // este evento es cuando arrastramos la ventana por la pantalla
        this.setLocation(x-xMouse,y- yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(Color.red);
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
         btnExit.setBackground(Color.white);
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void txtIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIniciarSesionMouseEntered
        btnIniciarSesion.setBackground(new Color(245,215,187));
    }//GEN-LAST:event_txtIniciarSesionMouseEntered

    private void txtIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIniciarSesionMouseExited
        btnIniciarSesion.setBackground(new Color(211,165,129));
    }//GEN-LAST:event_txtIniciarSesionMouseExited

    private void cajaUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaUsuarioMousePressed
        if(cajaUsuario.getText().equals("Ingresar nombre de usuario")){
            cajaUsuario.setText("");
            cajaUsuario.setForeground(Color.BLACK);
        }
        if(String.copyValueOf(cajaContrasena.getPassword()).isEmpty()){
            cajaContrasena.setText("*********");
            cajaContrasena.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_cajaUsuarioMousePressed

    private void cajaContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaContrasenaMousePressed
        if(String.copyValueOf(cajaContrasena.getPassword()).equals("*********")){
            cajaContrasena.setText("");
            cajaContrasena.setForeground(Color.BLACK);
        }
        if(cajaUsuario.getText().isEmpty()){
            cajaUsuario.setText("Ingresar nombre de usuario");
            cajaUsuario.setForeground(new Color(204, 204, 204));
            
        }
    }//GEN-LAST:event_cajaContrasenaMousePressed

    private void txtIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIniciarSesionMouseClicked
        datosIniciarSesion datos = new datosIniciarSesion();
           conexionUsuarios conUser = new conexionUsuarios();
           
           if(!((cajaUsuario.getText().equals("") || cajaUsuario.getText().equals("Ingresar nombre de usuario")) || (String.copyValueOf(cajaContrasena.getPassword()).isEmpty() || String.copyValueOf(cajaContrasena.getPassword()).equals("*********")))){
           
                datos.setNameUser(cajaUsuario.getText());
                datos.setPassUser(String.copyValueOf(cajaContrasena.getPassword()));
                if(conUser.IniciarSesionLogin(datos)){
                    
                    Principal pagina = new Principal();
                    pagina.setVisible(true);
                    dispose();
                } else {
                    limpiarCampos();
                }
                
         }
    }//GEN-LAST:event_txtIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LoginIcono1;
    private javax.swing.JLabel LoginIcono2;
    private javax.swing.JPanel backGround;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnIniciarSesion;
    private javax.swing.JPasswordField cajaContrasena;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtContrasena;
    private javax.swing.JLabel txtExit;
    private javax.swing.JLabel txtIniciarSesion;
    private javax.swing.JLabel txtNombreEmpresa;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void centrarPantalla() {
        Dimension tamanioVentana = getSize();
        Dimension tamanioPantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int ejeX = (tamanioPantalla.width-tamanioVentana.width) / 2;
        int ejeY = (tamanioPantalla.height-tamanioVentana.height) / 2;
        
        setLocation(ejeX, ejeY);
    }
    
     public void limpiarCampos(){
        cajaContrasena.setText("");
    }
    
 
}
