/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion.PaginaPrincipal.main;

import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Caja;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Inventario;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Personal_Cocina;

import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Personal_Fancesa;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Principal;

import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Usuarios;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Ventas;
import CapaPresentacion.PaginaPrincipal.event.EventMenuSelected;
import CapaPresentacion.PaginaPrincipal.swing.ScrollBar;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author KENNY
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
        public static Ventana_Principal principalVentana;
        public static Ventana_Inventario inventario;
        public static Ventana_Ventas ventas;
        public static Ventana_Caja caja;
        public static Ventana_Personal_Fancesa fancesa;
        public static Ventana_Personal_Cocina cocina;
        public static Ventana_Usuarios users;
     

    public Principal() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        principalVentana=new Ventana_Principal();
        inventario = new Ventana_Inventario();
        ventas = new Ventana_Ventas();
        caja=new Ventana_Caja();
        fancesa=new Ventana_Personal_Fancesa();
        cocina = new Ventana_Personal_Cocina();
        users=new Ventana_Usuarios();
        
        
        
        menu1.initMoving(Principal.this);
        

        
        //esto es del las paginas que se muestran (princiapl, usuarios, personal, etc)
        //containerPage.setVerticalScrollBar(new ScrollBar()); //para poner un scroll mas bontio por si se utiliza
        
         menu1.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void seleccion (int index){
                
                //System.out.println(index);
                if (index == 0) {
                    setForm(principalVentana);
                } else if(index == 1) {
                    setForm(inventario);
                } else if (index == 2) {
                    setForm(ventas);
                }else if (index == 3) {
                    setForm(caja);
                }else if (index == 7) {
                    setForm(fancesa);
                }else if (index == 8) {
                    setForm(cocina);
                }else if (index == 9) {
                    setForm(users);
                }else if (index==10){
                    System.exit(0);
                }
               
            }
        });
         
          //iniciamos por defecto con la pagina principal
                setForm(new Ventana_Principal());
       
    }

    private void setForm(JComponent com){
        containerVentanas.removeAll();
        containerVentanas.add(com);
        containerVentanas.repaint();
        containerVentanas.revalidate();
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new CapaPresentacion.PaginaPrincipal.swing.PanelBorder();
        menu1 = new CapaPresentacion.PaginaPrincipal.componentes.Menu();
        containerVentanas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(242, 242, 242));
        panelBorder1.setPreferredSize(new java.awt.Dimension(1204, 700));

        containerVentanas.setOpaque(false);
        containerVentanas.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(containerVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addComponent(containerVentanas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel containerVentanas;
    private CapaPresentacion.PaginaPrincipal.componentes.Menu menu1;
    private CapaPresentacion.PaginaPrincipal.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
