/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CapaPresentacion.PaginaPrincipal.Ventanas;

import CapaPresentacion.PaginaPrincipal.Ventanas.VentanasProductos.VentanaRegistroTienda;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author KENNY
 */
public class Ventana_Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventana_Inventarios
     */
    public Ventana_Ventas() {
        initComponents();
            Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void Iniciar(){
        LocalDate hoy = LocalDate.now();  // Obtener la fecha actual
         DateTimeFormatter formateadorDia = DateTimeFormatter.ofPattern("EEEE ", new Locale("es", "ES")); //formateando para que solo me de el día
        cajaDia.setText(hoy.format(formateadorDia)); 
        
         DateTimeFormatter formateadorFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd ", new Locale("es", "ES"));
         cajaFechaActualVenta.setText(hoy.format(formateadorFecha));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTurno = new javax.swing.ButtonGroup();
        header1 = new CapaPresentacion.PaginaPrincipal.componentes.Header();
        graficoVentas = new CapaPresentacion.PaginaPrincipal.componentes.BarChart3DDemo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVentas = new CapaPresentacion.PaginaPrincipal.swing.Table();
        txtTituloVentas = new javax.swing.JLabel();
        cajaDia = new javax.swing.JTextField();
        cajaFechaActualVenta = new javax.swing.JTextField();
        rbtTodoDia = new javax.swing.JRadioButton();
        rbtManana = new javax.swing.JRadioButton();
        rbtTarde = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProductosTienda = new CapaPresentacion.PaginaPrincipal.swing.Table();
        btnCrearVenta = new javax.swing.JButton();
        btnReporteVenta = new javax.swing.JButton();
        btnCrearTienda = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout graficoVentasLayout = new javax.swing.GroupLayout(graficoVentas);
        graficoVentas.setLayout(graficoVentasLayout);
        graficoVentasLayout.setHorizontalGroup(
            graficoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        graficoVentasLayout.setVerticalGroup(
            graficoVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        tableVentas.setBackground(new java.awt.Color(255, 255, 255));
        tableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVentas);

        txtTituloVentas.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        txtTituloVentas.setForeground(new java.awt.Color(0, 0, 0));
        txtTituloVentas.setText("VENTAS DEL DÍA");

        cajaDia.setEditable(false);
        cajaDia.setBackground(new java.awt.Color(242, 242, 242));
        cajaDia.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        cajaDia.setBorder(null);

        cajaFechaActualVenta.setEditable(false);
        cajaFechaActualVenta.setBackground(new java.awt.Color(242, 242, 242));
        cajaFechaActualVenta.setFont(new java.awt.Font("Roboto Black", 1, 20)); // NOI18N
        cajaFechaActualVenta.setBorder(null);

        btnGroupTurno.add(rbtTodoDia);
        rbtTodoDia.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        rbtTodoDia.setForeground(new java.awt.Color(0, 0, 0));
        rbtTodoDia.setSelected(true);
        rbtTodoDia.setText("TODO EL DÍA");

        btnGroupTurno.add(rbtManana);
        rbtManana.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        rbtManana.setForeground(new java.awt.Color(0, 0, 0));
        rbtManana.setText("MAÑANA");

        btnGroupTurno.add(rbtTarde);
        rbtTarde.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        rbtTarde.setForeground(new java.awt.Color(0, 0, 0));
        rbtTarde.setText("TARDE");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TURNO:");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRODUCTOS EN TIENDA");

        tableProductosTienda.setBackground(new java.awt.Color(255, 255, 255));
        tableProductosTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableProductosTienda);

        btnCrearVenta.setBackground(new java.awt.Color(64, 0, 17));
        btnCrearVenta.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnCrearVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/anadir-amigo.png"))); // NOI18N
        btnCrearVenta.setText("Crear Venta");
        btnCrearVenta.setBorder(null);
        btnCrearVenta.setBorderPainted(false);
        btnCrearVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearVentaMouseExited(evt);
            }
        });
        btnCrearVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVentaActionPerformed(evt);
            }
        });

        btnReporteVenta.setBackground(new java.awt.Color(64, 0, 17));
        btnReporteVenta.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnReporteVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/anadir-amigo.png"))); // NOI18N
        btnReporteVenta.setText("Reportes");
        btnReporteVenta.setBorder(null);
        btnReporteVenta.setBorderPainted(false);
        btnReporteVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteVentaMouseExited(evt);
            }
        });
        btnReporteVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentaActionPerformed(evt);
            }
        });

        btnCrearTienda.setBackground(new java.awt.Color(64, 0, 17));
        btnCrearTienda.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnCrearTienda.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearTienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/anadir-amigo.png"))); // NOI18N
        btnCrearTienda.setText("Crear Tienda");
        btnCrearTienda.setBorder(null);
        btnCrearTienda.setBorderPainted(false);
        btnCrearTienda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearTienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearTiendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearTiendaMouseExited(evt);
            }
        });
        btnCrearTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTiendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(graficoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCrearVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReporteVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCrearTienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtTituloVentas)
                                    .addGap(47, 47, 47)
                                    .addComponent(cajaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(cajaFechaActualVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(rbtTodoDia)
                        .addGap(49, 49, 49)
                        .addComponent(rbtManana)
                        .addGap(49, 49, 49)
                        .addComponent(rbtTarde)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrearVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrearTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReporteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(graficoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaFechaActualVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloVentas)
                        .addGap(33, 33, 33)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtTodoDia)
                    .addComponent(rbtManana)
                    .addComponent(rbtTarde)
                    .addComponent(jLabel2))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearVentaMouseEntered
        btnCrearVenta.setBackground(new Color(143,27,48));
    }//GEN-LAST:event_btnCrearVentaMouseEntered

    private void btnCrearVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearVentaMouseExited
        btnCrearVenta.setBackground(new Color(64,0,17)); //[64,87,68]
    }//GEN-LAST:event_btnCrearVentaMouseExited

    private void btnCrearVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVentaActionPerformed
        

    }//GEN-LAST:event_btnCrearVentaActionPerformed

    private void btnReporteVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteVentaMouseEntered
       btnReporteVenta.setBackground(new Color(143,27,48));
    }//GEN-LAST:event_btnReporteVentaMouseEntered

    private void btnReporteVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteVentaMouseExited
       btnReporteVenta.setBackground(new Color(64,0,17)); //[64,87,68]
    }//GEN-LAST:event_btnReporteVentaMouseExited

    private void btnReporteVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteVentaActionPerformed

    private void btnCrearTiendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearTiendaMouseEntered
       btnCrearTienda.setBackground(new Color(143,27,48));
    }//GEN-LAST:event_btnCrearTiendaMouseEntered

    private void btnCrearTiendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearTiendaMouseExited
        btnCrearTienda.setBackground(new Color(64,0,17)); //[64,87,68]
    }//GEN-LAST:event_btnCrearTiendaMouseExited

    private void btnCrearTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTiendaActionPerformed
        VentanaRegistroTienda tienda = new VentanaRegistroTienda();
        tienda.setVisible(true);
    }//GEN-LAST:event_btnCrearTiendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearTienda;
    private javax.swing.JButton btnCrearVenta;
    private javax.swing.ButtonGroup btnGroupTurno;
    private javax.swing.JButton btnReporteVenta;
    private javax.swing.JTextField cajaDia;
    private javax.swing.JTextField cajaFechaActualVenta;
    private CapaPresentacion.PaginaPrincipal.componentes.BarChart3DDemo graficoVentas;
    private CapaPresentacion.PaginaPrincipal.componentes.Header header1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtManana;
    private javax.swing.JRadioButton rbtTarde;
    private javax.swing.JRadioButton rbtTodoDia;
    private CapaPresentacion.PaginaPrincipal.swing.Table tableProductosTienda;
    private CapaPresentacion.PaginaPrincipal.swing.Table tableVentas;
    private javax.swing.JLabel txtTituloVentas;
    // End of variables declaration//GEN-END:variables
}
