/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion.PaginaPrincipal.Ventanas.VentanasUsuarios;

import CapaDatos.Usuarios_Personal.datosPersonalCocina;
import CapaLogica.Usuarios_Personal.conexionPersonalCocina;
import static CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Personal_Cocina.accion;
import static CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Personal_Cocina.idBuscar;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Personal_Cocina;
import CapaLogica.ExpresionesRegulares;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Principal;
import CapaPresentacion.PaginaPrincipal.Ventanas.Ventana_Usuarios;
import static CapaPresentacion.PaginaPrincipal.main.Principal.containerVentanas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.filechooser.FileNameExtensionFilter;
import static CapaPresentacion.PaginaPrincipal.main.Principal.cocina;
import static CapaPresentacion.PaginaPrincipal.main.Principal.users;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author KENNY
 */
public class Ventana_PersonalCocina_Registro extends javax.swing.JFrame {
    public static String IdPersonaBuscar="";
    ExpresionesRegulares expresiones= new ExpresionesRegulares();
    
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    
    int xMouse,  yMouse;
    String rutaImage = "";
    /**
     * Creates new form Ventana_PersonalCocina_Registro
     */
    public Ventana_PersonalCocina_Registro() {
        
        initComponents();
        cajaFecha.setText(formato.format(new Date()));
        centrarPantalla();
        iniciarId();
        inhabilitar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoEstadoPersonalCocina = new javax.swing.ButtonGroup();
        vent_Inicial1 = new CapaPresentacion.PaginaPrincipal.Ventanas.VentanasUsuarios.Vent_Inicial();
        cajaFoto = new javax.swing.JLabel();
        btnSubir = new javax.swing.JButton();
        btnEliminarFoto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cajaIdPersonal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaCi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cajaApP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaApM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cajaCargo = new javax.swing.JComboBox<>();
        cajaEdad = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaSueldo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cajaFecha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jrbtnActivo = new javax.swing.JRadioButton();
        jrbtnInactivo = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        headerVentana = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();
        btnPagos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        cajaFoto.setBackground(new java.awt.Color(255, 255, 255));
        cajaFoto.setText("Foto");
        cajaFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSubir.setBackground(new java.awt.Color(204, 204, 204));
        btnSubir.setForeground(new java.awt.Color(255, 255, 255));
        btnSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/incrementar.png"))); // NOI18N
        btnSubir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubirMouseExited(evt);
            }
        });
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        btnEliminarFoto.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar.png"))); // NOI18N
        btnEliminarFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarFotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarFotoMouseExited(evt);
            }
        });
        btnEliminarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFotoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Personal:");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CI:");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido Paterno:");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellido Materno:");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teléfono:");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cargo:");

        cajaCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "RESP ALMACEN", "COCINERO", "CAJERO", "LLEVADOR" }));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edad:");

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sueldo:");

        jLabel12.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha Contratación:");

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Estado:");

        GrupoEstadoPersonalCocina.add(jrbtnActivo);
        jrbtnActivo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jrbtnActivo.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnActivo.setSelected(true);
        jrbtnActivo.setText("Activo");
        jrbtnActivo.setContentAreaFilled(false);
        jrbtnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnActivoActionPerformed(evt);
            }
        });

        GrupoEstadoPersonalCocina.add(jrbtnInactivo);
        jrbtnInactivo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jrbtnInactivo.setForeground(new java.awt.Color(255, 255, 255));
        jrbtnInactivo.setText("Inactivo");
        jrbtnInactivo.setContentAreaFilled(false);

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/disquete.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(null);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/borrar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendar1PropertyChange(evt);
            }
        });

        headerVentana.setOpaque(false);
        headerVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerVentanaMouseDragged(evt);
            }
        });
        headerVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerVentanaMousePressed(evt);
            }
        });

        btnExit.setOpaque(false);

        txtExit.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerVentanaLayout = new javax.swing.GroupLayout(headerVentana);
        headerVentana.setLayout(headerVentanaLayout);
        headerVentanaLayout.setHorizontalGroup(
            headerVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerVentanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerVentanaLayout.setVerticalGroup(
            headerVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerVentanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPagos.setBackground(new java.awt.Color(204, 204, 204));
        btnPagos.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnPagos.setForeground(new java.awt.Color(0, 0, 0));
        btnPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/ImagenBillete.png"))); // NOI18N
        btnPagos.setText("PAGOS");
        btnPagos.setBorder(null);
        btnPagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagos.setFocusPainted(false);
        btnPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagosMouseExited(evt);
            }
        });
        btnPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vent_Inicial1Layout = new javax.swing.GroupLayout(vent_Inicial1);
        vent_Inicial1.setLayout(vent_Inicial1Layout);
        vent_Inicial1Layout.setHorizontalGroup(
            vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cajaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, vent_Inicial1Layout.createSequentialGroup()
                            .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnEliminarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vent_Inicial1Layout.createSequentialGroup()
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addContainerGap())
                    .addGroup(vent_Inicial1Layout.createSequentialGroup()
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                    .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                            .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(42, 42, 42))
                                        .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(101, 101, 101)))
                                    .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cajaApP, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cajaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cajaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cajaApM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cajaIdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(97, 97, 97)
                                    .addComponent(jrbtnActivo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jrbtnInactivo)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(95, 95, 95)
                                .addComponent(cajaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vent_Inicial1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cajaCi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(cajaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vent_Inicial1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vent_Inicial1Layout.createSequentialGroup()
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        vent_Inicial1Layout.setVerticalGroup(
            vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vent_Inicial1Layout.createSequentialGroup()
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(cajaIdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cajaApP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cajaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cajaApM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cajaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vent_Inicial1Layout.createSequentialGroup()
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cajaCi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cajaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vent_Inicial1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarFoto)
                            .addComponent(btnSubir))
                        .addGap(40, 40, 40)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jrbtnActivo)
                            .addComponent(jrbtnInactivo)))
                    .addGroup(vent_Inicial1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vent_Inicial1Layout.createSequentialGroup()
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cajaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cajaCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(vent_Inicial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(cajaSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vent_Inicial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vent_Inicial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtnActivoActionPerformed

    private void headerVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerVentanaMousePressed
        xMouse = evt.getX(); //me da la posicion en el eje X de la ventana
        yMouse = evt.getY();//me da la posicion en el eje Y de la ventana
    }//GEN-LAST:event_headerVentanaMousePressed

    private void headerVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerVentanaMouseDragged
         int x = evt.getXOnScreen();//esto captura en todo momento donde se encuentra la ventana
         int y = evt.getYOnScreen();
        // este evento es cuando arrastramos la ventana por la pantalla
        this.setLocation(x-xMouse,y- yMouse);
    }//GEN-LAST:event_headerVentanaMouseDragged

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        //idBuscar="";
        dispose();
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        //btnExit.setBackground(Color.red);
        txtExit.setForeground(Color.RED);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        //btnExit.setBackground(Color.white);
        txtExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_txtExitMouseExited

    private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendar1PropertyChange
        //esto es para que la fecha escogida en el calendario se muestre en la caja FechaContratacion
        if (evt.getOldValue()!= null) {  //verificamos que hayamos escogido una fecha
             //damos un formato a la fecha
            
            cajaFecha.setText(formato.format(jCalendar1.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jCalendar1PropertyChange

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(cajaNombre.getText().length()==0) {//esta vacio
            JOptionPane.showConfirmDialog(null, "Ingrese nombre de la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaNombre.requestFocus();
            return;
        }
        if(!expresiones.validarNombres(cajaNombre.getText())){
            JOptionPane.showConfirmDialog(null, "Ingrese un nombre correcto","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaNombre.requestFocus();
            return;
        } 
        
        
         if(cajaApP.getText().length()==0) {//esta vacio
            JOptionPane.showConfirmDialog(null, "Ingrese apellido paterno de la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaApP.requestFocus();
            return;
        }
         
         if(!expresiones.validarNombres(cajaApP.getText())){
            JOptionPane.showConfirmDialog(null, "Ingrese un apellido paterno correcto","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaApP.requestFocus();
            return;
        } 
         
          if(cajaApM.getText().length()==0) {//esta vacio
            JOptionPane.showConfirmDialog(null, "Ingrese apellido materno de la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaApM.requestFocus();
            return;
        }
          
           if(!expresiones.validarNombres(cajaApM.getText())){
            JOptionPane.showConfirmDialog(null, "Ingrese un apellido materno correcto","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaApM.requestFocus();
            return;
        } 
          
           
           if(cajaCi.getText().length()==0) {//esta vacio
            JOptionPane.showConfirmDialog(null, "Ingrese CI de la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaCi.requestFocus();
            return;
        }
           
           if(!expresiones.validarCarnet(cajaCi.getText())){
            JOptionPane.showConfirmDialog(null, "Ingrese un carnet de identidad correcto","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaCi.requestFocus();
            return;
        } 
           
           //el telefono puede estar vacio
           
           if(cajaTelefono.getText().length()!=0){
               if(!expresiones.validarTelefono(cajaTelefono.getText())){
                JOptionPane.showConfirmDialog(null, "Ingrese un teléfono correcto","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                cajaTelefono.requestFocus();
                return;
               }
           }
           
            if(cajaDireccion.getText().length()==0) {//esta vacio
            JOptionPane.showConfirmDialog(null, "Ingrese dirección de la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaDireccion.requestFocus();
            return;
        }
            
            if(!expresiones.validarDireccion(cajaDireccion.getText())){
                JOptionPane.showConfirmDialog(null, "Ingrese una dirección correcta","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                cajaDireccion.requestFocus();
                return;
               }
            
            
            
            
             if((Integer)cajaEdad.getValue()<10 ||  (Integer)cajaEdad.getValue()>100 ) {//esta vacio
            JOptionPane.showConfirmDialog(null, "La edad debe ser mayor a 10 y menor a 100","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaEdad.requestFocus();
            return;
        }
             //del cargo no preguntamos porque si o si estará ya uno escogido por defecto, asi que todo bien ahi
             
              if(cajaSueldo.getText().length()==0 ) {//esta vacio
            JOptionPane.showConfirmDialog(null, "Ingrese sueldo de la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
            cajaSueldo.requestFocus();
            return;     
        }
             
              if(!expresiones.validarSueldo(cajaSueldo.getText())){
                JOptionPane.showConfirmDialog(null, "Ingrese un sueldo correcto","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                cajaSueldo.requestFocus();
                return;
               }
              
              
              
              
              datosPersonalCocina datos = new datosPersonalCocina();
              conexionPersonalCocina fun = new conexionPersonalCocina();
              
              datos.setIdPersona(cajaIdPersonal.getText());
              datos.setNombre(cajaNombre.getText());
              datos.setApellidoP(cajaApP.getText());
              datos.setApellidoM(cajaApM.getText());
              datos.setCi(cajaCi.getText());
              datos.setTelefono(cajaTelefono.getText());
              datos.setDireccion(cajaDireccion.getText());
              datos.setEdad((int)cajaEdad.getValue());
              datos.setSueldo(Float.parseFloat(cajaSueldo.getText()));
              datos.setCargo(cajaCargo.getSelectedItem().toString()); 
              //para obtener el valor del radio button
                            Enumeration<AbstractButton> btnGrp = GrupoEstadoPersonalCocina.getElements();
                            String resultado = "";
                            while(btnGrp.hasMoreElements()){
                                JRadioButton btnAux = (JRadioButton)btnGrp.nextElement();
                                if(btnAux.isSelected()){
                                    resultado = btnAux.getText();
                                    break;
                                }
                            }
                            String res="A";
                            if(resultado=="Inactivo"){
                                res="X";
                            }
              datos.setEstado(res);
              datos.setFechaContratacion(cajaFecha.getText());
        
              datos.setNombreImagen(null);//esto debemos eliminarlo
              
              
              if(rutaImage!=""){
                  datos.setFoto(getImage(rutaImage));
              } else {
                  datos.setFoto(null);
              }
              
              
              
              if (accion == "crear"){
                  if(fun.insertarDatos(datos)){
                      JOptionPane.showConfirmDialog(null, "Persona registrada","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                      accion="guardar";
                  }
              } else {
                  if(fun.editarDatos(datos)){
                      JOptionPane.showConfirmDialog(null, "Persona editada","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                  }
                   
              }
              
                    users= new Ventana_Usuarios();
                    setForm(users);
                    
                    cocina = new Ventana_Personal_Cocina();
                    setForm(cocina);
                    
                    
                    
              
             
    }//GEN-LAST:event_btnGuardarActionPerformed

    //esto es para guardar la imagen como bytea en postgres
    
    private byte [] getImage(String ruta){
        File imagen = new File (ruta);
        try {
            byte [] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;
        } catch(Exception e ){
            return null;
         }
    }
    
    
    
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        datosPersonalCocina datos = new datosPersonalCocina();
        conexionPersonalCocina fun = new conexionPersonalCocina();
        if (fun.verificarRegistroExistente(cajaIdPersonal.getText())==1){
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Desea eliminar a la persona?","Confirmar",2);
            if(confirmacion==0){
                    datos.setIdPersona(cajaIdPersonal.getText());
                    fun.eliminarDatos(datos);
                    JOptionPane.showConfirmDialog(null, "Persona eliminada","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    users= new Ventana_Usuarios();
                    setForm(users);
                    cocina = new Ventana_Personal_Cocina();
                    setForm(cocina);
                    
                    
                    
                    
                    
                }
        }
        else {
             
             JOptionPane.showConfirmDialog(null, "No existe la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
       //esto es para que al escoger el archivo se vea como el sistema de windows
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Ventana_PersonalCocina_Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
               
        
        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter filtradoExtension = new FileNameExtensionFilter("JPG, PNG", "jpg", "png");
        filechooser.setFileFilter(filtradoExtension);
        
        if (filechooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaImage = filechooser.getSelectedFile().getAbsolutePath();
            Image imagen = new ImageIcon(rutaImage).getImage(); //obtenemos la imagen de la ruta
            ImageIcon mIcono = new ImageIcon(imagen.getScaledInstance(cajaFoto.getWidth(), cajaFoto.getHeight(), 0)); //ajistamos la imagen a la caj donde se almacenara
            cajaFoto.setIcon(mIcono); //mostramos la imagen en la caja
            
        }
        
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnEliminarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFotoActionPerformed
         ImageIcon image = new ImageIcon(getClass().getResource("/Files/ImagenUsuarios.png"));
         Icon icono = new ImageIcon(image.getImage().getScaledInstance(cajaFoto.getWidth(), cajaFoto.getHeight(), 0));
        cajaFoto.setIcon(icono);
         rutaImage="";
    }//GEN-LAST:event_btnEliminarFotoActionPerformed

    private void btnSubirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseEntered
        btnSubir.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_btnSubirMouseEntered

    private void btnSubirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubirMouseExited
        btnSubir.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnSubirMouseExited

    private void btnEliminarFotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFotoMouseEntered
        btnEliminarFoto.setBackground(new Color(33,33,33));
        
    }//GEN-LAST:event_btnEliminarFotoMouseEntered

    private void btnEliminarFotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarFotoMouseExited
       btnEliminarFoto.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btnEliminarFotoMouseExited

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(33,33,33));
        btnGuardar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(204,204,204));
        btnGuardar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(33,33,33));
        btnEliminar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
         btnEliminar.setBackground(new Color(204,204,204));
        btnEliminar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnPagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseEntered
        btnPagos.setBackground(new Color(33,33,33));
        btnPagos.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnPagosMouseEntered

    private void btnPagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagosMouseExited
        btnPagos.setBackground(new Color(204,204,204));
        btnPagos.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnPagosMouseExited

    private void btnPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosActionPerformed
       if(accion=="crear"){
           JOptionPane.showConfirmDialog(null, "Primero cree a la persona","VENTANA DE INFORMACIÓN", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
       }
       else if(accion=="guardar"){
            Ventana_PersonalCocina_Pagos pagos= new Ventana_PersonalCocina_Pagos() ;

            //System.out.println(idBuscar);
            pagos.setVisible(true);
            dispose();
            
       }
    }//GEN-LAST:event_btnPagosActionPerformed


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_PersonalCocina_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_PersonalCocina_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_PersonalCocina_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_PersonalCocina_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_PersonalCocina_Registro().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoEstadoPersonalCocina;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarFoto;
    private javax.swing.JPanel btnExit;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnSubir;
    private javax.swing.JTextField cajaApM;
    private javax.swing.JTextField cajaApP;
    private javax.swing.JComboBox<String> cajaCargo;
    private javax.swing.JTextField cajaCi;
    private javax.swing.JTextField cajaDireccion;
    private javax.swing.JSpinner cajaEdad;
    private javax.swing.JTextField cajaFecha;
    private javax.swing.JLabel cajaFoto;
    private javax.swing.JTextField cajaIdPersonal;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaSueldo;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JPanel headerVentana;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jrbtnActivo;
    private javax.swing.JRadioButton jrbtnInactivo;
    private javax.swing.JLabel txtExit;
    private CapaPresentacion.PaginaPrincipal.Ventanas.VentanasUsuarios.Vent_Inicial vent_Inicial1;
    // End of variables declaration//GEN-END:variables
    
    
    private void centrarPantalla() {
        Dimension tamanioVentana = getSize();
        Dimension tamanioPantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int ejeX = (tamanioPantalla.width-tamanioVentana.width) / 2;
        int ejeY = (tamanioPantalla.height-tamanioVentana.height) / 2;
        
        setLocation(ejeX, ejeY);
    }
    
    private void inhabilitar(){
        cajaIdPersonal.setEnabled(false);
        cajaFecha.setEnabled(false);
        
    }
    
    /*private void iniciarId(){
        if (idBuscar =="") {
            generarID();
        } else {
            conexionPersonalCocina fun = new conexionPersonalCocina();
            String[] registro = fun.devolverDatos(idBuscar);
            if(registro!= null) {
                cajaIdPersonal.setText(registro[0]);
                cajaNombre.setText(registro[1]);
                cajaApP.setText(registro[2]);
                cajaApM.setText(registro[3]);
                cajaCi.setText(registro[4]);
                cajaTelefono.setText(registro[5]);
                cajaDireccion.setText(registro[6]);
                cajaEdad.setValue(Integer.valueOf(registro[7]));
                cajaSueldo.setText(registro[8]);
                cajaCargo.setSelectedItem(registro[9]);
                if(registro[10].equals("X")){
                    jrbtnInactivo.setSelected(true);
                }
                cajaFecha.setText(registro[11]);
            }
        }
        idBuscar="";
    
    }*/
    
    private void iniciarId(){
        if (idBuscar =="") {
            generarID();
        } else {
            conexionPersonalCocina fun = new conexionPersonalCocina();
            datosPersonalCocina registro = fun.devolverDatos(idBuscar);
            if(registro!= null) {
                IdPersonaBuscar=idBuscar;
                cajaIdPersonal.setText(registro.getIdPersona());
                cajaNombre.setText(registro.getNombre());
                cajaApP.setText(registro.getApellidoP());
                cajaApM.setText(registro.getApellidoM());
                cajaCi.setText(registro.getCi());
                cajaTelefono.setText(registro.getTelefono());
                cajaDireccion.setText(registro.getDireccion());
                cajaEdad.setValue(registro.getEdad());
                cajaSueldo.setText(String.valueOf(registro.getSueldo()));
                cajaCargo.setSelectedItem(registro.getCargo());
                if(registro.getEstado().equals("X")){
                    jrbtnInactivo.setSelected(true);
                }
                cajaFecha.setText(registro.getFechaContratacion());
                
                try{
                    byte[] imagen = registro.getFoto();
                    BufferedImage bufferImage = null;
                    InputStream inputstream = new ByteArrayInputStream(imagen);
                    bufferImage = ImageIO.read(inputstream);
                    ImageIcon nIcono = new ImageIcon(bufferImage.getScaledInstance(172, 150, 0));
                    cajaFoto.setIcon(nIcono);
                    rutaImage="";
                } catch(Exception e){
                    sinFotoDePerfil();
                }
            }
        }
        idBuscar="";
    
    }
    private void sinFotoDePerfil(){
                        ImageIcon image = new ImageIcon(getClass().getResource("/Files/ImagenUsuarios.png"));
                        Icon icono = new ImageIcon(image.getImage().getScaledInstance(cajaFoto.getWidth(), cajaFoto.getHeight(), 0));
                       cajaFoto.setIcon(icono);
    }
    
    private void generarID(){
        conexionPersonalCocina fun= new conexionPersonalCocina();
        DecimalFormat formato = new DecimalFormat("0000");
        cajaIdPersonal.setText(formato.format(fun.generarIdpersonal()));
         sinFotoDePerfil();
    }

    
    private void setForm(JComponent com){
                   containerVentanas.removeAll();
                    containerVentanas.add(com); ///TENER CUIDADO CON ESTO O MODIFICARLO, REVISAR BIEN, ES PARA VOLVER A PINTAR LAS VENTANAS EN CASO DE MODIFICACIONES
                    containerVentanas.repaint();
                    containerVentanas.revalidate();
    
    }
}
